# Generated by Django 4.1.1 on 2022-11-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_description_en_product_description_tr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_en',
            new_name='name_ru',
        ),
    ]
