# Generated by Django 4.1.1 on 2022-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_name_en_product_name_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paind',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('vaiting', 'VAITING'), ('confirmed', 'CONFIRMED'), ('paid', 'PAID'), ('delivered', 'DELIVERED')], default='VAITING', max_length=100, null=True),
        ),
    ]
