# Generated by Django 4.1.1 on 2022-12-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_stop_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description_ru',
        ),
    ]
